### ISSUE TITLE
 'Realm/Realm.h' file not found

### ISSUE THREAD

**Issue by alessandrostone** [matthewcheok/Realm-JSON#2]
/Pods/Realm+JSON/Realm+JSON/RLMObject+JSON.h:9:9: 'Realm/Realm.h' file not found

I have updated to 0.1.2 ad now it's not able to find that...

any idea?

**Comment by irichardson** [comment]
Hey I am also getting this issue now this Realm+JSON (0.2.5) and Realm (0.90.5). Any suggestions?
