### ISSUE TITLE
Error: 'Realm/RLMPlatform.h' file not found in Realm.h

### ISSUE THREAD

**Issue by leofto** [matthewcheok/Realm-JSON#25]
Podfile: 

pod "Realm+JSON"
----
Using Realm (0.90.1)
Using Realm+JSON (0.2.4)

I get that error after a fresh pod install.

**Comment by matthewcheok** [comment]
Just updated the podspec for Realm 0.90.x
You shouldn't need to explicitly include the Realm pod
