### ISSUE TITLE
Memory management issues with createOrUpdateInRealm:withJSONArray

### ISSUE THREAD

**Issue by ransomweaver** [matthewcheok/Realm-JSON#30]
This might be a bug or just some extra documentation for a particular use case.

I have a dataset in the tens of thousands of json objects my app is batch-downloading at the first install of the app (thereafter it updates with changed content only). For network performance I like to take batches of 2500-5000, but i find that if I give that array to Realm all at once using    createOrUpdateInRealm:withJSONArray it takes too much RAM (especially on older devices) and I get a memory warning.

Maybe this could be dealt with internally to Realm+JSON, but my solution externally is to iteratively feed subarrays to Realm. The key is @autoreleasepool; that frees the memory on each loop so that it doesn't climb beyond what is allocated to write kItemsPerRun of the dataset. 

        int ct = props.count;
        if (ct > 0) {
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
                    int kItemsPerRun = 1000;
                    int runIndex = 0;
                    NSArray *tmpArr = nil;
                    while (runIndex < ct) {
                        int length = MIN( ct - runIndex, kItemsPerRun );
                        tmpArr = [props subarrayWithRange: NSMakeRange( runIndex, length )];
                        runIndex += kItemsPerRun;
                        @autoreleasepool {
                            RLMRealm * realm = [RLMRealm defaultRealm];
                            [realm beginWriteTransaction];
                            [VProperty createOrUpdateInRealm:realm withJSONArray:tmpArr];
                            [realm commitWriteTransaction];
                        }
                    }
            });

**Comment by matthewcheok** [comment]
This should work in 0.2.6

```
RLMRealm * realm = [RLMRealm defaultRealm];
[realm beginWriteTransaction];
[VProperty createOrUpdateInRealm:realm props];
[realm commitWriteTransaction];
```
