### ISSUE TITLE
How to map array of strings

### ISSUE THREAD

**Issue by davidmuzi** [matthewcheok/Realm-JSON#4]
Part of the JSON response Im trying to model is an array of strings.  How do I map this with Realm-JSON?

I tried using RLMArrays with another class, but am unsure how to map the string values.  Here is a sample JSON model:

....
`"currency":"USD", "genres":["Games", "Entertainment", "Action", "Adventure"], "genreIds":["6014", "6016", "7001", "7002"]`
....

**Comment by benvium** [comment]
@matthewcheok This is very useful! Could this "self" -> "propertyName" mapping be promoted to the documentation?
