### ISSUE TITLE
Transforming ID from JSON to create object

### ISSUE THREAD

**Issue by marlowcharite** [matthewcheok/Realm-JSON#41]
Hello, I'm having trouble transforming an `id` key which is returned as a string in JSON and mapping it to an `NSInteger` type called `ID` which I use as my primary key. Any suggestions? I crash with a null exception for `ID`.

**Comment by matthewcheok** [comment]
Ideally you would use a JSON number if you want it to translate to an integer in your model.

If you can't change the JSON response, you can always use a transformer:

```
+ (NSValueTransformer *)IDJSONTransfomer {
    return ...
}
```

You might see how we've implemented several built-in transformers including MCJSONDateTransformer and [this](http://nshipster.com/nsvaluetransformer/) might be useful.
