### ISSUE TITLE
Crash on processing nil date

### ISSUE THREAD

**Issue by mpaulsonco** [matthewcheok/Realm-JSON#46]
Realm can handle nil objects if you provide a default value with ```defaultPropertyValues```.

MCJSONDateTransformer crashes at ```[self.formatter dateFromString:value];``` if value is nil.

**Comment by mpaulsonco** [comment]
@matthewcheok I wanted to see if you have any thoughts on my suggest contribution.

**Comment by matthewcheok** [comment]
Sorry for the late reply. Similar issue [here](https://github.com/matthewcheok/Realm-JSON/issues/51) maybe? Looks good
