### ISSUE TITLE
Handling of date strings?

### ISSUE THREAD

**Issue by komocode** [matthewcheok/Realm-JSON#55]
I have part of this JSON incoming data:
```javascript
date_created = "2015-08-26T06:27:36.000Z";
```
How does Realm-JSON handle parsing of that string into my property of a model:
```objective-c
@property NSDate *dateCreated;
```
I already have set up
```objective-c
+ (NSDictionary *)JSONInboundMappingDictionary
```
to recognize the difference in the key names. But it doesn't parse the string into an NSDate.

**Comment by matthewcheok** [comment]
Did you supply the relevant transformer?

**Comment by komocode** [comment]
I'm unfamiliar with that. I see your documentation about the value transformer, but wasn't sure what it did. Let me figure this out and I'll get back to you.

**Comment by komocode** [comment]
I understand it now. My issue is resolved.
