### ISSUE TITLE
How to parse an array of string

### ISSUE THREAD

**Issue by tuantm2014** [matthewcheok/Realm-JSON#60]
Does anyone know how to parse an array of string. Like this:

```js
"zoneInfo": {
    "tariffInfoLines": [
        "In this city you pay per minute."
    ]
}
```

We have a zoneInfo object that contains a tariffInfoLines array. This tariffInfoLines array contains strings. To store in Realm, i define RealmString object and store it in RLMArray

```Objective-C
@interface RealmString : RLMObject
@property NSString *stringValue;
@end
@implementation RealmString
@end

RLM_ARRAY_TYPE(RealmString)

@interface TariffInfo : RLMObject
@property RLMArray<RealmString> *storedTariffInfoLines;
@end
```

But i dont know how to parse it from JSON using Realm-JSON. The application will crash if you try to. So i really need some help to solve this problem!

**Comment by matthewcheok** [comment]
That's because you haven't defined the mapping for `stringValue`:

```
@interface RealmString : RLMObject
@property NSString *stringValue;
@end
@implementation RealmString
+ (NSDictionary *)JSONInboundMappingDictionary {
  return @{
         @"self": @"stringValue",
  };
}
@end
```

**Comment by tuantm2014** [comment]
Thanks @matthewcheok but it seems not work. It still crash at line 190 of `RLMObject+JSON.m`

```Objective-C
for (id item in(NSArray*) value) {
	[array addObject:[elementClass mc_createObjectFromJSONDictionary:item]];
}
```
Because `item` is type of `NSString` not `NSDictionary`

**Comment by matthewcheok** [comment]
Your issue looks very similar to matthewcheok/Realm-JSON#4 Mind sharing your code sample?

**Comment by tuantm2014** [comment]
Oh, it works now after clean database and project. Thanks so much @matthewcheok
