### ISSUE TITLE
Custom date format in MCJSONDateTransformer

### ISSUE THREAD

**Issue by AntiVIRUZ** [matthewcheok/Realm-JSON#61]
Why in MCJSONDateTransformer are there only three date's formats? For some reasons i'm getting date like "yy.MM.dd' 'hh:mm", and I can't parse it by this transport. Maybe should add method like valueTransformerWithDateFormat:(NSString *) or (NSDateFormat*)? If you accept it, i'll write it.

**Comment by matthewcheok** [comment]
Because this format is less commonly used, it's not provided out of the box. You can always create and use your own `NSValueTransformer` which you can build using the provided ones as a reference. If you think this is useful enough to be added to the library, I'll be happy to accept it.
